name: aspacewithmeaning
favicon: null
layout_spectrum: 0.2702500051818788
typography_spectrum: 0.7526328342501074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffad2'
    - '#ebc4b7'
    - '#150704'
    - '#685b3b'
    - '#a79496'
  brandStrength: 0.75
  lightness: 0.20363601599819958
  saturation: 0.6686135756317526
  rhythmicContrast: 0.08744910592213273
purpose: []
